runtime: nodejs20

env: standard

instance_class: F1  # Lowest cost instance (free tier eligible)

automatic_scaling:
  min_instances: 0  # Scale to zero when not in use (lowest cost)
  max_instances: 1  # Single instance for low usage
  target_cpu_utilization: 0.6

env_variables:
  NODE_ENV: production
  PORT: 8080
  DATABASE_PATH: /tmp/database.sqlite  # Local path - synced with Cloud Storage
  GCS_BUCKET_NAME: '${GCS_BUCKET_NAME}'  # Set in GCP Console -> Cloud Storage bucket name
  DB_FILE_NAME: 'database.sqlite'  # Database file name in Cloud Storage
  JWT_SECRET: '${JWT_SECRET}'  # Set in GCP Console -> Secret Manager
  FRONTEND_URL: 'https://www.matsplash.com'
  CORS_ORIGIN: 'https://www.matsplash.com'
  VITE_LOGIN_SECRET_PATH: '${LOGIN_SECRET_PATH}'  # Set in GCP Console -> Secret Manager
  # Note: App Engine automatically provides GOOGLE_APPLICATION_CREDENTIALS

handlers:
  # API routes must come first (more specific)
  - url: /api/.*
    script: auto
    
  # Serve static files from dist folder
  - url: /(.*\.(js|css|ico|png|jpg|svg|woff|woff2|ttf|eot))
    static_files: dist/\1
    upload: dist/(.*\.(js|css|ico|png|jpg|svg|woff|woff2|ttf|eot))
    expiration: 1y

  # Serve index.html for all other routes (SPA routing)
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html

# Database Persistence:
# Cloud Storage sync is implemented - database automatically syncs on startup/shutdown
# See server/services/cloudStorage.ts for implementation details

