runtime: nodejs20

env: standard

# Region: europe-west (Belgium) - App Engine and Cloud Storage in same region to minimize network costs
# Note: App Engine Standard requires region to be set during initial deployment
instance_class: F1  # Lowest cost instance (free tier eligible)

automatic_scaling:
  min_instances: 0  # Scale to zero when not in use (lowest cost)
  max_instances: 1  # Single instance for low usage
  target_cpu_utilization: 0.6

env_variables:
  NODE_ENV: production
  PORT: 8080
  DATABASE_PATH: /tmp/database.sqlite  # Local path - synced with Cloud Storage
  GCS_BUCKET_NAME: 'matsplash-fin-db-host-dev-378703'  # Cloud Storage bucket in EU (europe-west region)
  DB_FILE_NAME: 'database.sqlite'  # Database file name in Cloud Storage
  JWT_SECRET: 'Hs34gmCQl6xYrMSAiOtczpRywUVoILJE'  # Generated secure secret
  FRONTEND_URL: 'https://www.matsplash.com'
  CORS_ORIGIN: 'https://www.matsplash.com'
  VITE_LOGIN_SECRET_PATH: 'matsplash-fin-2jg1wCHqcMOEhlBr'  # Generated secure login path
  # Note: App Engine automatically provides GOOGLE_APPLICATION_CREDENTIALS

handlers:
  # API routes must come first (more specific)
  - url: /api/.*
    script: auto
    
  # Serve static files from dist folder
  - url: /(.*\.(js|css|ico|png|jpg|svg|woff|woff2|ttf|eot))
    static_files: dist/\1
    upload: dist/(.*\.(js|css|ico|png|jpg|svg|woff|woff2|ttf|eot))
    expiration: 365d

  # Serve index.html for all other routes (SPA routing)
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html

# Database Persistence:
# Cloud Storage sync is implemented - database automatically syncs on startup/shutdown
# See server/services/cloudStorage.ts for implementation details

